/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2014 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::daughterDistribution

Description

SourceFiles
    daughterDistribution.C

\*---------------------------------------------------------------------------*/

#ifndef daughterDistribution_H
#define daughterDistribution_H

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //


namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class daughterDistribution Declaration
\*---------------------------------------------------------------------------*/

class daughterDistribution
{
protected:

    // Protected data

        //- Reference to turbulence model
        const incompressible::momentumTransportModel& turbulence_;

public:

    // Constructors

        //- Construct from a phase pair
        daughterDistribution(const incompressible::momentumTransportModel& turbulence);


    //- Destructor
    virtual ~daughterDistribution();


    // Member Functions
        
        virtual tmp<DimensionedField<scalar, volMesh>> distribution
        (
            const DimensionedField<scalar, volMesh>&,
            int
        ) const = 0;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#ifdef NoRepository
    #include "daughterDistribution.C"
#endif

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
