#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeLnInclude micromixing
wmake $targetType micromixing
wmake $targetType

#------------------------------------------------------------------------------

