#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd lapack/
make clean
cd ..

wclean libso solutionNMC
wclean libso populationBalance
wclean

#------------------------------------------------------------------------------
